"""Exact desktop desk markup derived from the approved uploaded prototype."""

DESK = r'''<section class="deskhome desk" aria-label="Arafat Rahaman portfolio desk">
 <div class="clock-surface desktop-clock" role="img" aria-label="Live analogue clock showing Dhaka time"><span class="hand hour"></span><span class="hand minute"></span><span class="hand second"></span><span class="pin"></span></div>
 <div class="steam" aria-hidden="true"><i></i><i></i><i></i></div>
 <img class="wind-leaf one" src="assets/home/reference-leaf.webp" alt="" aria-hidden="true"><img class="wind-leaf two" src="assets/home/reference-leaf.webp" alt="" aria-hidden="true"><img class="wind-leaf three" src="assets/home/reference-leaf.webp" alt="" aria-hidden="true">
 <header class="site-header"><a class="brand" href="./"><strong>Arafat Rahaman</strong><small>Journalist</small></a><nav aria-label="Main navigation"><a href="#top" aria-current="page">Home</a><a href="about/">About</a><a href="all-work/">Work</a><a href="case-studies/">Case studies</a><a href="collections/">Collections</a><a href="contact/">Contact</a></nav><span class="location">Dhaka, Bangladesh<br><time id="dhaka-time">--:--:--</time></span></header>
 <div class="mobile-top"><figure class="mobile-portrait"><img src="assets/home/reference-portrait.webp" alt="Arafat Rahaman smiling outdoors"><figcaption><strong>Arafat Rahaman</strong><span>Staff Reporter, The Daily Star</span></figcaption></figure><div class="mobile-cup" aria-hidden="true"><img src="assets/home/reference-cup.webp" alt=""><div class="steam"><i></i><i></i><i></i></div></div><div class="mobile-clock-wrap"><div class="clock-surface mobile-clock" role="img" aria-label="Live analogue clock showing Dhaka time"><span class="hand hour"></span><span class="hand minute"></span><span class="hand second"></span><span class="pin"></span></div><span>Dhaka time <time id="mobile-dhaka-time">--:--:--</time></span></div></div>
 <img class="portrait-photo" src="assets/home/reference-portrait.webp" alt="Arafat Rahaman smiling outdoors"><div class="portrait-caption"><strong>Arafat Rahaman</strong><span>Staff Reporter, The Daily Star</span></div>
 <section class="intro"><span class="overline">Stories from</span><h1>People,<br>places and<br>possibilities</h1><p>I cover education and write on governance, human rights, social justice, youth and civic movements, and public accountability in Bangladesh.</p><a class="button" href="#work">Explore my work <span aria-hidden="true">↓</span></a></section>
 <nav class="category-grid" id="work" aria-label="Explore my work"><a class="desk-card reporting" href="reporting/" aria-label="Explore Reporting"><span class="card-photo crop-reporting" aria-hidden="true"></span><span class="card-label">Reporting<span aria-hidden="true">→</span></span></a><a class="desk-card opinion" href="opinion/" aria-label="Explore Opinion & analysis"><span class="card-photo crop-opinion" aria-hidden="true"></span><span class="card-label">Opinion &amp; analysis<span aria-hidden="true">→</span></span></a><a class="desk-card thoughts" href="thoughts/" aria-label="Explore Thoughts"><span class="card-photo crop-thoughts" aria-hidden="true"></span><span class="card-label">Thoughts<span aria-hidden="true">→</span></span></a><a class="desk-card photography" href="photography/" aria-label="Explore Photography"><span class="card-photo crop-photography" aria-hidden="true"></span><span class="card-label">Photography<span aria-hidden="true">→</span></span></a></nav>
 <footer class="desk-signoff" id="contact"><div class="signoff-main"><div class="signoff-invite"><span class="signoff-label">Have a story?</span><a class="signoff-contact" href="contact/">Get in touch <span aria-hidden="true">↗</span></a></div><nav class="signoff-links" aria-label="Contact and published work"><a href="all-work/">All work</a><a href="case-studies/">Case studies</a><a href="collections/">Beats & series</a><a href="mailto:arafat.mcj@yahoo.com">Email</a><a href="https://bd.linkedin.com/in/arafat-rahaman" target="_blank" rel="noopener">LinkedIn</a><a href="https://www.thedailystar.net/author/arafat-rahaman" target="_blank" rel="noopener">The Daily Star</a></nav></div><div class="signoff-base"><span>© <span id="footer-year">2026</span> Arafat Rahaman</span><span>Dhaka, Bangladesh</span><button class="motion-button" type="button" aria-pressed="false">Pause ambience</button></div></footer>
</section>'''
